### ISSUE TITLE
keyless signing in GitHub Actions

### ISSUE THREAD

**Issue by jbpratt** [sigstore/cosign#1205]
Key-less signing of a container image inside of GitHub Actions: `failed to decode timestamp.json: expired at 2021-12-14 18:48:47 +0000 UTC`

We [install](https://github.com/ContainerCraft/kmi/blob/1015ba569d504146b61fa2707e25f3240a6dfd7c/.github/workflows/test.yml#L54) `cosign` via the GitHub action. [Action with failure](https://github.com/ContainerCraft/kmi/runs/4525124402?check_suite_focus=true). We had 4-5 jobs fail within 30 minutes with this same error.

```
Generating ephemeral keys...
Retrieving signed certificate...
retrieving trusted root; local cache may be corrupt: updating from remote TUF repository: updating tuf metadata: tuf: failed to decode timestamp.json: expired at 2021-12-14 18:48:47 +0000 UTC
panic: error retrieving CT public key

goroutine 1 [running]:
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.getCTPub()
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:47 +0x13a
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.verifySCT({0xc0002fa800, 0x432, 0x7c0}, {0xc000decc30, 0xe2, 0xe4})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:57 +0x45
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier.NewSigner({0x2a6a1b0, 0xc00005e0d0}, {0xc000ec2600, 0xc0005df658}, {0x25c55dc, 0xc00000e020}, {0x258984f, 0x1}, {0x2a24060, 0xc0008fa390})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go:79 +0x8d
github.com/sigstore/cosign/cmd/cosign/cli/sign.keylessSigner({0x2a6a1b0, 0xc00005e0d0}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, 0x1e}, {0x25b3dda, ...}, ...})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign/sign.go:402 +0x1ab
github.com/sigstore/cosign/cmd/cosign/cli/sign.SignerFromKeyOpts({0x2a6a1b0, 0xc00005e0d0}, {0x0, 0x203000}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, ...}, ...})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign/sign.go:425 +0x128
github.com/sigstore/cosign/cmd/cosign/cli/sign.SignCmd({_, _}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x25bf377, 0x1e}, {0x25b3dda, ...}, ...}, ...)
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign/sign.go:117 +0x245
github.com/sigstore/cosign/cmd/cosign/cli.Sign.func1(0xc0008fd680, {0xc0008edc60, 0x1, 0x2})
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/cli/sign.go:92 +0x3d6
github.com/spf13/cobra.(*Command).execute(0xc0008fd680, {0xc0008edc40, 0x2, 0x2})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000374c80)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/sigstore/cosign@v1.4.1/cmd/cosign/main.go:45 +0x4c
```

**Comment by dlorenc** [comment]
cc @asraa

**Comment by asraa** [comment]
OMG I suppose https://github.com/sigstore/root-signing/blob/03ceeb24fe67705c2df9248da65690cfb2ddf4a7/.github/workflows/snapshot-timestamp.yml#L8 did not trigger. Manually triggering and updating. Give it 20 min to go through. Thank you -- I will make this weekly so we don't run into this.

**Comment by asraa** [comment]
Should be fixed. Let me know, please close it if it is!
