### ISSUE TITLE
panic: The environment variable "SYSTEM_NAMESPACE" is not set

### ISSUE THREAD

**Issue by vmulpuru** [sigstore/cosign#1692]
When executing cosign 1.6.0 binary on Ubuntu 20.04 in WSL2, it fails with a panic.

```
~ (@kind-kind) $ cosigned-linux-amd64
2022/03/30 17:42:46 {
  "gitVersion": "v1.6.0",
  "gitCommit": "4b2c3c0c8ee97f31b9dac3859b40e0a48b8648ee",
  "gitTreeState": "clean",
  "buildDate": "'2022-03-03T17:59:06Z'",
  "goVersion": "go1.17.7",
  "compiler": "gc",
  "platform": "linux/amd64"
}
2022/03/30 17:42:46 Registering 3 clients
2022/03/30 17:42:46 Registering 3 informer factories
2022/03/30 17:42:46 Registering 4 informers
2022/03/30 17:42:46 Registering 4 controllers
panic: The environment variable "SYSTEM_NAMESPACE" is not set

If this is a process running on Kubernetes, then it should be using the downward
API to initialize this variable via:

  env:
  - name: SYSTEM_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

If this is a Go unit test consuming system.Namespace() then it should add the
following import:

import (
        _ "knative.dev/pkg/system/testing"
)

goroutine 1 [running]:
knative.dev/pkg/system.Namespace()
        knative.dev/pkg@v0.0.0-20220202132633-df430fa0dd96/system/env.go:39 +0xa5
knative.dev/pkg/injection/clients/namespacedkube/informers/factory.withInformerFactory({0x243e310, 0xc000715590})
        knative.dev/pkg@v0.0.0-20220202132633-df430fa0dd96/injection/clients/namespacedkube/informers/factory/factory.go:42 +0x85
knative.dev/pkg/injection.(*impl).SetupInformers(0x243e310, {0x243e310, 0xc000815b90}, 0x3689b38)
        knative.dev/pkg@v0.0.0-20220202132633-df430fa0dd96/injection/informers.go:110 +0xfd
knative.dev/pkg/injection.EnableInjectionOrDie({0x243e310, 0xc000a9ec90}, 0xc0001bbb78)
        knative.dev/pkg@v0.0.0-20220202132633-df430fa0dd96/injection/injection.go:58 +0x11c
knative.dev/pkg/injection/sharedmain.MainWithConfig({0x243e310, 0xc000a9ec90}, {0x2109351, 0x8}, 0xc000826240, {0xc0001bbeb0, 0x4, 0x4})
        knative.dev/pkg@v0.0.0-20220202132633-df430fa0dd96/injection/sharedmain/main.go:203 +0x27a
knative.dev/pkg/injection/sharedmain.MainWithContext({0x243e310, 0xc000a9ec90}, {0x2109351, 0x8}, {0xc0001bbeb0, 0x4, 0x4})
        knative.dev/pkg@v0.0.0-20220202132633-df430fa0dd96/injection/sharedmain/main.go:169 +0xe7
main.main()
        github.com/sigstore/cosign/cmd/cosign/webhook/main.go:66 +0x2e9
```

**Comment by dlorenc** [comment]
> cosigned-linux-amd64

It looks like you're executing the `cosigned` binary, not the `cosign` binary. `cosigned` is meant to be run in a kubernetes environment as a policy system for Kubernetes.

**Comment by dlorenc** [comment]
Sorry didn't mean to close there.

**Comment by vmulpuru** [comment]
Using the right cosign binary worked as expected.
