### ISSUE TITLE
verify unsigned local image throws panic error

### ISSUE THREAD

**Issue by choukri-m** [sigstore/cosign#2655]
**Description**

verifying a local image (i.e. image saved using cosign save) leads to dereferencing a nil pointer if the image was not signed before saving. I know we should not save an unsigned image but as I was doing unit tests to catch this kind of errors when verifying an unsigned image.

the steps to replicate this are:

1. using `cosign save --dir TEST-DIR`, store on disk an image that has not been signed (only tested from a private registry)
2. run `cosign verify --local-image TEST-DIR` on this image

This leads to panic

The solution could be added in `cosign/pkg/cosign/verify.go > VerifyLocalImageSignatures` by adding a check for nil pointer after sigs are returned from `sigs, err := se.Signatures()`
or return an error when no signatures found in `cosign/pkg/oci/layout/index.go > Signatures`

**Version**

v2.0.0-rc.0
it might be on older versions too

**Comment by hectorj2f** [comment]
I quickly ran into the same issue. It seems `sigs` in nil so it causes this panic: 

```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x102bb700c]

goroutine 1 [running]:
github.com/sigstore/cosign/v2/pkg/cosign.verifySignatures({0x104929df0, 0x14000056080}, {0x0?, 0x0?}, {{0x103e019b5?, 0x14000faa800?}, {0x14001009900?, 0x1?}}, 0x1?)
	github.com/sigstore/cosign/v2/pkg/cosign/verify.go:548 +0x4c
github.com/sigstore/cosign/v2/pkg/cosign.VerifyLocalImageSignatures({0x104929df0, 0x14000056080}, {0x16db4f94e?, 0x140002c3f50?}, 0x140005ad840)
	github.com/sigstore/cosign/v2/pkg/cosign/verify.go:544 +0x1a0
github.com/sigstore/cosign/v2/cmd/cosign/cli/verify.(*VerifyCommand).Exec(0x140005ada10, {0x104929df0, 0x14000056080}, {0x140007ce5c0, 0x1, 0x14000184c80?})
	github.com/sigstore/cosign/v2/cmd/cosign/cli/verify/verify.go:263 +0xc90
github.com/sigstore/cosign/v2/cmd/cosign/cli.Verify.func1(0x14000825800, {0x140007ce5c0, 0x1, 0x4})
	github.com/sigstore/cosign/v2/cmd/cosign/cli/verify.go:132 +0x2c4
github.com/spf13/cobra.(*Command).execute(0x14000825800, {0x140007ce580, 0x4, 0x4})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000456600)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	github.com/sigstore/cosign/v2/cmd/cosign/main.go:62 +0x58
```
